### ISSUE TITLE
Error running the container: "dh key too small"

### ISSUE THREAD

**Issue by dionysius** [AlBundy33/keeweb_kdbx4_hotfix#1]
```
...
2024-08-29 03:28:33 keeweb  | >> exec docker CMD
2024-08-29 03:28:33 keeweb  | nginx
2024-08-29 03:28:33 keeweb  | 2024/08/29 03:28:33 [emerg] 1#1: SSL_CTX_set_tmp_dh("/etc/nginx/external/dh.pem") failed (SSL: error:0A00018A:SSL routines::dh key too small)
2024-08-29 03:28:33 keeweb  | nginx: [emerg] SSL_CTX_set_tmp_dh("/etc/nginx/external/dh.pem") failed (SSL: error:0A00018A:SSL routines::dh key too small)
```

**Comment by dionysius** [comment]
wtf are these bots...

**Comment by dionysius** [comment]
Well since I'm only using this temporarily, I replaced `dh.pem` contents with those from https://security.stackexchange.com/questions/94390/whats-the-purpose-of-dh-parameters but no luck, guess I'll have to setup a certificate myself

**Comment by dionysius** [comment]
Hmm... after switching up dh.pem and and the cert/key I still couldn't figure out to make nginx happy...
```
2024-08-29 03:55:30 keeweb  | 2024/08/29 03:55:30 [info] 11#11: *4 SSL_do_handshake() failed (SSL: error:0A000416:SSL routines::ssl/tls alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 172.18.0.1, server: 0.0.0.0:443
```

---

Well seems like my browser is not liking any certificate, how to turn it dumb 💩 ...

**Comment by dionysius** [comment]
Yay starting a chromium based browser with `--ignore-certificate-errors` did the trick. I'm now stuck with:

![image](https://github.com/user-attachments/assets/a9833d26-6ba9-4c9b-b4ab-cf37642f5329)

I noticed the config.json is a folder (?) and not a file...

**Comment by dionysius** [comment]
```diff
diff --git a/config.json b/config.json
new file mode 100644
index 0000000..4782c43
--- /dev/null
+++ b/config.json
@@ -0,0 +1,4 @@
+{
+    "settings": {
+    }
+}
\ No newline at end of file
diff --git a/docker-compose.yml b/docker-compose.yml
index 2784518..7c0c95d 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -12,7 +12,9 @@ services:
     container_name: keeweb
     volumes:
       - ./certs:/etc/nginx/external/
-      - ./config.json:/keeweb/config.json
+      - type: bind
+        source: ./config.json
+        target: /keeweb/config.json
     ports:
       - '9080:80/tcp'
       - '9443:443/tcp'
```

A valid but fairly empty config file had to be provided and to be correctly mounted as a file it seems...

After a fresh `docker compose up` I could finally load my file

**Comment by dionysius** [comment]
Hmm... resaving and/or resetting the password and then downloading the file did not help for keepass, still getting the base64 error as described in https://github.com/keeweb/keeweb/issues/2001...

Is there a step I am missing?

**Comment by AlBundy33** [comment]
during creation of the Dockerfile I had to change the DH_SIZE from 512 to 1024
It seems that nginx now wants 2048
-> value can be changed with environment-variable DH_SIZE

I've updated the Dockerfile with the new DH_SIZE and also added an empty example file for config.json

**Comment by AlBundy33** [comment]
> ```diff
> diff --git a/config.json b/config.json
> new file mode 100644
> index 0000000..4782c43
> --- /dev/null
> +++ b/config.json
> @@ -0,0 +1,4 @@
> +{
> +    "settings": {
> +    }
> +}
> \ No newline at end of file
> diff --git a/docker-compose.yml b/docker-compose.yml
> index 2784518..7c0c95d 100644
> --- a/docker-compose.yml
> +++ b/docker-compose.yml
> @@ -12,7 +12,9 @@ services:
>      container_name: keeweb
>      volumes:
>        - ./certs:/etc/nginx/external/
> -      - ./config.json:/keeweb/config.json
> +      - type: bind
> +        source: ./config.json
> +        target: /keeweb/config.json
>      ports:
>        - '9080:80/tcp'
>        - '9443:443/tcp'
> ```
> 
> A valid but fairly empty config file had to be provided and to be correctly mounted as a file it seems...
> 
> After a fresh `docker compose up` I could finally load my file

There is no need to change the mount options - if you mount `./foo.bar:/etc/foo.bar` and your local foo.bar does not exists it is created as directory (standard docker behavior).
If the file exists it is mounted as file in the container.

**Comment by AlBundy33** [comment]
> Hmm... resaving and/or resetting the password and then downloading the file did not help for keepass, still getting the base64 error as described in [keeweb/keeweb#2001](https://github.com/keeweb/keeweb/issues/2001)...
> 
> Is there a step I am missing?

To be honest I don't exactly remember where I had this issue.
I did some successful local tests (create database in keepass, load it in keepas web, made some modifications, save, export, load in Keepass)

You only have to:
- clone the repo
- if you don't have a config.json copy config.json.example to config.json
- optionally run `docker builder prune` if you don't want to use previous builded cached layers
- run `docker compose up` (this builds the image automatically)

Maybe use a private session in your browser to ensure that the current app is loaded.

**Comment by AlBundy33** [comment]
@dionysius works the updated Dockerfile for you?

**Comment by dionysius** [comment]
Unfortunately I get to try it earliest tomorrow/this weekend. I'll let you know

**Comment by dionysius** [comment]
Soo, I had no luck. clean build cache, no containers, no images, it started a fresh build but it wouldn't fix my file. Possible if the error is still the guy in front of the screen, me. **But it doesn't matter**, I've taken a working snapshot from the past and added the few entries back into the working one.

![image](https://github.com/user-attachments/assets/2b362c61-0d36-44f9-a235-26f5fbafb1e6)
These were my settings, a kdbx file with only a master password

**Comment by AlBundy33** [comment]
and can you open the modified file now in keeweb and keepass?
And save it in one app and ooen it again in the other app?

one fix was also to change the database settings in keeweb from kdbx4 to kdbx3.
and don't forget to test keeweb in private mode - I tested with a local db and sometimes the database was loaded from browser storage if not in private mode.
